### ISSUE TITLE
ROSWorld prep: robot is not visible in Ignition

### ISSUE THREAD

**Issue by AndyZe** [hello-robot/stretch_ros2#6]
Consider me kind of a beta tester for ROS World. I'm not extremely familiar with Docker but I'm attempting to follow the Readme for Docker installation. I'm on Ubuntu 20 and the `ros_world2021` branch.

Using this command from Docker:

`ros2 launch stretch_ignition ignition.launch.py`

The robot is not shown and I get warnings about the costmap.

@vatanaksoytezer 

![stretch_robot_not_visible](https://user-images.githubusercontent.com/11284393/137592748-f52811a8-75b9-4535-8fe6-730570124cbd.png)

**Comment by AndyZe** [comment]
Probably related to these errors:

`[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [model://stretch_description/meshes/link_gripper_finger_left.STL]`

**Comment by vatanaksoytezer** [comment]
Should be fixed with the new docker I forgot to change the export paths that was the only problem. If you can docker pull and re-do the instructions should be all good, lmk how it goes.

**Comment by AndyZe** [comment]
thanks!
