### ISSUE TITLE
IMU frame name mismatch between the URDF and the driver

### ISSUE THREAD

**Issue by marekmlk** [hello-robot/stretch_ros2#97]
Hello!
In [the URDF](https://github.com/hello-robot/stretch_ros2/blob/humble/stretch_description/urdf/stretch_base_imu.xacro#L5) IMU's link is called `base_imu` whereas is [the driver](https://github.com/hello-robot/stretch_ros2/blob/humble/stretch_core/stretch_core/stretch_driver.py#L430) IMU message is published with `imu_mobile_base` frame.

Kind regards,
Marek

**Comment by hello-binit** [comment]
Hi @marekmlk, thanks for letting me know. I'll look into this and get back to you soon.

**Comment by hello-binit** [comment]
Hi @marekmlk, a fix for this issue was just merged in.

**Comment by marekmlk** [comment]
Thank you!
